### ISSUE TITLE
Is this library still maintained ?

### ISSUE THREAD

**Issue by AkechiShiro** [paragbaxi/qualysapi#110]
Hi,

This library looks like it is not actively maintained.

I would like to know if the maintainer such as @paragbaxi could tell us if the library is still usable or not to this day.

**Comment by AkechiShiro** [comment]
@kraigu you're not missing any actions or any API methods from the official upstream API of Qualys ? For instance #109, this ?

**Comment by kraigu** [comment]
No, I don't use those. When we need new features, we add them ourselves and push back here, but it's been a while since we needed something new.

**Comment by AkechiShiro** [comment]
Okay thanks for making that clear, any idea also if there is any official documentation, usually for tools that's what's made but my understanding is, that since this project is not official, there is no clear documentation on how to use it, which is kinda of sad from a dev standpoint.

**Comment by kraigu** [comment]
No, it is not official. Qualys has a community manager but I've yet to successfully engage them on this.
To be clear, I'm not the or even a maintainer, although the code did originate from my organisation. Parag rewrote big chunks of it though.

**Comment by AkechiShiro** [comment]
Also shouldn't there be a community chat Matrix/IRC/Discord/Slack whatever channel maybe on [Libera.chat](https://libera.chat/) servers for newcomers or new contributors looking to help but I guess there are really not much contributors right ?

**Comment by kraigu** [comment]
It's not a very active community, no. :) Ideally Qualys would officially support this and provide such resources.

**Comment by paragbaxi** [comment]
i am no longer a customer/employee of qualys. so I am not actively maintaining it. i am open to adding maintainers. 

ps: I've found that money as an incentive only goes so far. this started as a passion project. having said that, a Rust implementation would be awesome!

**Comment by AkechiShiro** [comment]
That's true @paragbaxi but right now I'm working full time and also doing Google Summer Of Code 2022 adding another project would be too presumptious of my capacity to achieve all of what is asked of me, especially if no money is involved, it is just that working on a library for a proprietary software suite doesn't ring well with my ethics, I prefer working on an Open Source Qualys equivalent so that the security of anyone gets better as a whole, not behind a paywall.

But in the future after GSoC I might give a try to rework either this library or build a new one maybe, I'm not 100% sure yet.
