### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by dswhite42** [paragbaxi/qualysapi#14]
Hello.  Are there any plans to migrate this package to Python 3?  I was able to make a usable version with 2to3 and a few minor tweaks, but it'd be nice to see an official version!

Thanks.

**Comment by paragbaxi** [comment]
Hi dswhite42, no plans to port to 3. I'd be interested in seeing your 2to3 port fork.

**Comment by dswhite42** [comment]
Here it is:
https://app.box.com/s/bcd56lee3tcw242wr6m8455wld9xwstx
