### ISSUE TITLE
Need a collaborator

### ISSUE THREAD

**Issue by paragbaxi** [paragbaxi/qualysapi#15]
Hi folks, I will not be able to give this package the TLC it deserves. I'm looking for someone to takeover. Any volunteers?

**Comment by zany2dmax** [comment]
Hi Parag, give me a call at 6785707792 and I'll see about transferring it to me.

**Comment by paragbaxi** [comment]
Jeff, very kind of you to volunteer. I think you're a perfect fit for this. I will add you as a collaborator shortly.
