### ISSUE TITLE
Integrated with web applications for large systems

### ISSUE THREAD

**Issue by SkyLeach** [paragbaxi/qualysapi#16]
So I've been plunking around withing qualysapi for a few weeks to see if it will/can handle what I/we need (essentially enterprise-level massive network stuff [million+hosts].

The short answer is no, not as it is.  The good ansewr is that it's light enoguh to be a decent base.  As such I've started implementing some internal changes I think others may be interested in so I'm putting this in as an interest-level feeler.  if interest is sufficiently high, I will either fork the project or contribute the code (whatever, doesn't matter much to me).

The changes I have implemented include the following:
- progressively changing named keyword arguments to _args/_*kwargs with default kwargs.pop(default)
- adding credential injection to the connect method from util rather than assuming a configuration file
- adding an API cache (redis) layer that can be specified in the config or connect argument.  This layer effectively just builds keys based on api parameters and endpoints.  This basically makes a responsive qualys interface that doesn't hammer qualys to death and possibly saturate your account limits.  In addition, qualys often requires multiple api calls in order to return information to map report names to ids using the query apis.  Especially for automation this is a bit of a drag.
- adding stream handling for large results.  In stream handling mode, the requests API is configured to stream the raw results to an lxml parsing iterator which the calling code can then implement and begin operating on results without waiting.
- byte unicode to utf-8 encoded unicode.
- python3 support

Lemme know.

**Comment by vjirasek** [comment]
Hi, definitely interested, especially in the redis cache. I believe the best way is to fork as Parag no longer maintains this code.

**Comment by SkyLeach** [comment]
Ok.  Once I'm done with some Q/A (stress testing) and expanding the cache control api I'll fork the project (unless Parag wants to consider letting me do a version release on this repo.  Given the number of google links to this package it may be worth considering).

**Comment by zany2dmax** [comment]
You can release under this. I can authorize it.

**Comment by SkyLeach** [comment]
I have pushed up the 4.1.1-develop branch and I will be pushing additional changes into this branch.  Testing and feedback during this process are welcomed.  I do not promise it will all work yet, but I will eventually tag 4.1.1-alpha and 4.1.1-beta branches as things get a bit further along.

Right now the branch includes the following major changes (all currently compatable with previous implementations using the qualysapi)

* I've changed the long specifically named arguments into kwargs with defaults using kwargs.pop('argname', default) so that additional arguments can be passed through to extensions without disrupting the library
* I've created a tests module with test_data pseudo-module for loading unit tests without requiring a valid qualys username and password.
* I've also added in a capability for username and password to be requested a single time for running all unit tests (update and build a configuration in a tempfile and then remove it during setup and teardown of the unittest)
* I've added and done some initial testing with the qualys api cache
* I've added a method to handle large result sets using the raw requests callback which can then be added into an lxml iterable reader implementation (which I am now coding out).

**Known Issues:** I need to implement a partial stream reader for the raw results to check for errors and prevent caching of api calls returning errors.  There are other known features centered around this which need to be expanded a bit, and none of this has been sufficiently tested yet.

**Comment by SkyLeach** [comment]
Because of some issues with massive maps and map report generation as well as large data set processing I have decided to add in optional SMP/ASYNC integration.  This means that N maps can be loaded using the api v1 maplist and then the API can be instantiated to produce reports on these (or any subset of them) in a distributed process manager.  These report ids will be linked to the map object serialized to the cache, allowing one to check on the status of the maps without having to depend on map/report names (name the reports anything you want).

**Comment by SkyLeach** [comment]
Hey guys, I should really have already updated everyone on my situation.

I have received enough leeway (permission) to discuss my role in this and how it has changed.

I started working on the 4.1.1 branch as an initiative with Cisco.  That branch was used exclusively in python3.5 with multiprocessing and many trillions of Qualys records (about 8GB of new data/day over the Qualys API pipeline).

The code works (mostly), but it's probably ugly and definitely incomplete.  The group I was contracted to support lost funding for their initiative and I was moved to a different position.  This lateral move resulted in a loss of access to the data that I was using for development and QA of these enhanced features.

While I truly wish I had the time to create my own Qualys instance and continue to develop these powerful features, I simply do not.  I would also be limited in that I couldn't ever hope to generate anywhere near the volume of data I was testing that branch against.

With regret, therefore, I would ask that anyone else with an interest in high volume throughput with Qualys take over for me.  I will be more than happy to provide advice and/or support to anyone who does this.  Just ping me and I'll help as much as I'm able.

**Comment by paragbaxi** [comment]
check this out for a working example

https://github.com/paragbaxi/qualysguard_host_list_detection

**Comment by SkyLeach** [comment]
@paragbaxi you'll notice I was using multiprocessing instead of threads.  I did this because I was running this on an openstack virtualization cluster.  Processes can be forked off onto additional hardware, threads cannot.  The use of reddis was to allow access to the data without sharing the heap as well (a limitation in python for very large systems).

In general: if a concurrent processing design requires interprocess communication: use threads.  If it is a single channel for data (network->process->storage) then use processes to make the most of virtualization resources.

Use of filesystem output should be optional due to microservice adoption.  Most of the new designs for large-scale systems will be deploying microservices via docker or similar.  This allows access to OS-constrained services.  Saving to disk is slow(er) especially in large systems.  Use of memory caches for temporary storage is preferred.

Just some tips!  Good luck and nice work!
