### ISSUE TITLE
MemoryError when downloading big reports 

### ISSUE THREAD

**Issue by mircea-m** [paragbaxi/qualysapi#18]
Hi guys,

I'm getting MemoryError when I download a 700MB report (works fine for smaller reports, 10-15MB).
I can download the same 700MB report via curl call.
I’m using a Windows machine with 8GB of RAM.

Here is the output:

> > > import qualysapi
> > > a = qualysapi.connect()
> > > WARNING:root:config.ini permissions allows more than user access.
> > > rep = a.request('/api/2.0/fo/report', {'action': 'fetch', 'id': '7882'})
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python27\lib\site-packages\qualysapi\connector.py", line 310, in request
> > >     logger.debug('response text =\n%s' % (response))
> > > MemoryError

Thank you,
Mircea

**Comment by SkyLeach** [comment]
This is a known issue with the current api since it attempts to handle the entire data stream at the same time.

The new version will handle large reports as io streams using iterative parsing and/or disk caching, but it isn't ready yet.

**Comment by mircea-m** [comment]
Thank you for the update.

Mircea
