### ISSUE TITLE
How to get a list of tags?

### ISSUE THREAD

**Issue by gorivishal** [paragbaxi/qualysapi#19]
Is it possible to obtain a list of tags using qualysapi?

Eventually, I am looking to create an Asset Tag with a condition of IPRange = X.X.X.X to Y.Y.Y.Y 

Tried using Groovy but the documentation doesn't provide information if such a method as hasIPRange() exists.

Tried creating the file.xml as below but the error is simply not verbose enough.

    <?xml version="1.0" encoding="UTF-8"?>
     <ServiceRequest>
     <data>
      <Tag>
       <name>UnixQualysTag</name>
       <ruleType>Asset Search</ruleType>
       <TAG_CRITERIA><IP_RANGES><IP_RANGE>X.X.X.X-Y.Y.Y.Y</IP_RANGE></IP_RANGES></TAG_CRITERIA>
       <created>2014-02-06T19:14:50Z</created>
       <modified>2014-02-06T19:14:50Z</modified>
       <color>#FFFFFF</color>
      </Tag>
     </data>
    </ServiceRequest>

XX:qualys vgori$ curl -u "username:password" -H "Content-type: text/xml" -X "POST" --data-binary @- "https://qualysapi.qualys.com/qps/rest/2.0/create/am/tag" < ./file.xml 

Error:

    <?xml version="1.0" encoding="UTF-8"?>
    <ServiceResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://qualysapi.qualys.com/qps/xsd/2.0/am/tag.xsd">
      <responseCode>INVALID_REQUEST</responseCode>
      <responseErrorDetails>
        <errorMessage>modified: An error occurred while validating the element. Please contact your account manager..</errorMessage>
      </responseErrorDetails>
    </ServiceResponse>

**Comment by gorivishal** [comment]
I was able to figure out the xml format. It is as shown below:

<?xml version="1.0" encoding="UTF-8"?>
<ServiceRequest>
  <data>
    <Tag>
      <name>UnixQualysTag</name>
      <ruleText>&lt;TAG_CRITERIA&gt;&lt;IP_RANGES&gt;&lt;IP_RANGE&gt;10.172.104.102&lt;/IP_RANGE&gt;&lt;/IP_RANGES&gt;&lt;/TAG_CRITERIA&gt;</ruleText>
      <ruleType>ASSET_SEARCH</ruleType>
      <children>
        <list/>
      </children>
    </Tag>
  </data>
</ServiceRequest>

**Comment by zany2dmax** [comment]
Glad you figured it out!  YOu can also get a list of all tags using the qps/rest/2.0/search/am/tag/ API with an empty results XML POST data:
<?xml version="1.0" encoding="UTF-8" ?>
<ServiceRequest>
</ServiceRequest>
