### ISSUE TITLE
Encode User Creds

### ISSUE THREAD

**Issue by cutaway** [paragbaxi/qualysapi#27]
I recommend an update to the configuration file and credential parsing. Currently the credentials are in the clear. Obfuscating the credentials is preferred to prevent casual credential disclosure. Obfuscation is not security, but it does have its place. 

Update the qualysapi/config.py code:

```python
import base64 as b64
```

Change the 'get_auth' function from:

```python
def get_auth(self):
        ''' Returns username from the configfile. '''
        return (self._cfgparse.get('info', 'username'), self._cfgparse.get('info', 'password'))
```

to:

```python
def get_auth(self):
        ''' Returns username from the configfile. '''
        if self._cfgparse.get('info', 'encoded'):
            return (b64.decodestring(self._cfgparse.get('info', 'username')), b64.decodestring(self._cfgparse.get('info', 'password')))
        return (self._cfgparse.get('info', 'username'), self._cfgparse.get('info', 'password'))
```

Update the config file info block to include an 'encode' variable. It can be false if people don't want to use it.:

```python
[info]
#hostname = qualysapi.serviceprovider.com
encoded  = True
username = cHl0aG9uMi43
password = ISFPYmZ1c2NhdGlvbklzMkdvb2QhIQ==
```

Update the README to help people encode their credentials:

```python
user> ipython
In [1]: import base64 as b64

In [2]: b64.encodestring('python2.7').strip()
Out[2]: 'cHl0aG9uMi43'

In [3]: b64.encodestring('!!ObfuscationIs2Good!!').strip()
Out[3]: 'ISFPYmZ1c2NhdGlvbklzMkdvb2QhIQ=='
```

Go forth and do good things,
Cutaway

**Comment by paragbaxi** [comment]
Makes sense. Wanna fork it and I'll merge it in?

**Comment by cutaway** [comment]
Sure, give me a few days. Need to finish this project first.

**Comment by uovobw** [comment]
@cutaway any news on this one?

**Comment by paragbaxi** [comment]
still welcoming a PR

**Comment by lamusmaser** [comment]
I'll be writing a PR to accommodate this issue. Currently testing on my side, should be ready in a few days.
