### ISSUE TITLE
Revisit python3 porting plans

### ISSUE THREAD

**Issue by kraigu** [paragbaxi/qualysapi#31]
I wasn't sure if I should comment on #14 or open a new request, but I figured since in 2015 python3 support was a "sometime, maybe" thing and now it's a "soon, hopefully" request, I'd make a new one.

I can probably volunteer some time (either my own or somebody else's :) ) to do this if there's no current plans, although I think that would probably look like a fork without regards to maintaining any (deliberate) compatibility with 2.x.

**Comment by cclauss** [comment]
I would recommend a single codebase that supports both Python 2 and Python 3.  Without that we will have divergent evolution and an inability to do side-by-side testing.  With [__six__](http://six.readthedocs.io/) and other tools, it is not so hard to do.

**Comment by kraigu** [comment]
Sure, that's what I'd like to see too. :)

**Comment by paragbaxi** [comment]
Merged PR

**Comment by cclauss** [comment]
Can a new release to PyPI be made?  The current PyPI release fails in __setup.py__ on Python 3 because __execfile()__ was removed.  A current release would allow us to get feedback on what is still broken on Python 3 now that the code no longer has syntax errors or undefined names.

**Comment by paragbaxi** [comment]
qualysapi 5.0 released
https://pypi.org/manage/project/qualysapi/release/5.0.0/

**Comment by paragbaxi** [comment]
https://travis-ci.org/paragbaxi/qualysapi shows no errors for 2 or 3
