### ISSUE TITLE
Undefined names in contrib.py

### ISSUE THREAD

**Issue by cclauss** [paragbaxi/qualysapi#32]
https://travis-ci.org/paragbaxi/qualysapi/jobs/353189768#L478
* Three are linked to [this change](https://github.com/paragbaxi/qualysapi/commit/aa1591eedfd6224b857262a024d213e5d4d3fdbf#r28860657j).
* One is linked to [this TODO](https://github.com/paragbaxi/qualysapi/blob/master/qualysapi/contrib.py#L176)
* The two others are a mystery to me.

**Comment by cclauss** [comment]
* Three are linked to the change above.
* One is linked to [this TODO](https://github.com/paragbaxi/qualysapi/blob/master/qualysapi/contrib.py#L176)

**Comment by paragbaxi** [comment]
contrib.py was an old example of how to use the api. unlikely that it still works. removed file.
