### ISSUE TITLE
Python 2 parse module import error

### ISSUE THREAD

**Issue by yestinj** [paragbaxi/qualysapi#36]
When attempting to import this module in a test project I encountered a runtime import error regarding the urlparse module from urllib.parse (ImportError: No module named parse).

After some research I discovered that this module in urllib is Python 3 specific, and for Python 2 urlparse should be imported from the urlparse module. I've fixed this locally and it works under Python 2 and 3. 

I'm unsure if issue is only affecting me on my system, or if it is a real issue and applies to everyone. I'd appreciate if a maintainer could review it.

I'm happy to submit a pull request if this issue is considered valid.

![qualys-stacktrace](https://user-images.githubusercontent.com/1382137/39995509-b5840e90-577c-11e8-8a1e-ead41fea13f3.png)

**Comment by paragbaxi** [comment]
Yes, a PR would be great!
