### ISSUE TITLE
Changelog updates?

### ISSUE THREAD

**Issue by k4otix** [paragbaxi/qualysapi#38]
Appreciate all the work and recent activity, but any chance we can have the changelog maintained as well? Suddenly piprot in my CI/CD workflow is telling me I have dependencies that are 1400+ days out of date!  I then had to come here and start picking through merges to see what's been updated,  only to find the initial pushes of code with Python 3 support caused some issues with Python 2, etc. 

So some notes in the changelog about new features, compatibility changes, and bug fixes would be really helpful!

**Comment by paragbaxi** [comment]
sorry about python 2 issues. py3 has become the priority with redhat including it by default. i think we've fixed the py27 issues. can you confirm?
