### ISSUE TITLE
Mishandling of http request content bytes in Python 3

### ISSUE THREAD

**Issue by trolldbois** [paragbaxi/qualysapi#40]
https://github.com/paragbaxi/qualysapi/blob/c6a0e2216d14541109af6597ed2c3e107cfae27c/qualysapi/connector.py#L320

In python 3, this should read either
`response = request.content` that will return bytes
or if you absolutely want unicode repr:
`response = request.content.decode()` that will return a python 3 (unicode) string

why is this important ?
well right now, an api call in python 3 returns an unicode value of the python bytes string representation of the bytes returned by the request.
something like `"b\'this is from qualys\\nwith escaped escape characters\\r\\nNot easy to parse.\'"`
You can notice the leading `"b\'"` and ending `\'` that are problematic also.

instead of the expected `b'this is from qualys\nwith normal escape characters\r\neasy to parse.'`

**Comment by paragbaxi** [comment]
If you throw in a PR, I can merge it.

**Comment by lingfish** [comment]
Hi, I don't think this is 100% solved.  I've just tried some of my code with Python 3.5, and I initially got the error in this issue.

I then installed master, and was then getting:

```    root = objectify.fromstring(response)
  File "src/lxml/objectify.pyx", line 1801, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1872, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

Common talk out there suggests it should be returning `request.content` instead, but this then returns a bytes string, which then chokes qualysapi thusly:

```
  File "/home/jlingohr/.virtualenvs/qualys3.5/lib/python3.5/site-packages/qualysapi/connector.py", line 325, in request
    if not ('<responseCode>INVALID_REQUEST</responseCode>' in response and
TypeError: a bytes-like object is required, not 'str'
```

So I guess if `.content` is used, more patching is needed in the other `in` comparisons etc to internally convert back to something resembling a string :/

**Comment by paragbaxi** [comment]
@lingfish , should I revert #42?

**Comment by lingfish** [comment]
I don't think so; it seems to be a move forward.  The issue is that other stuff in your code needs to be adapted I think.

I've gotten around this for the moment by doing:

```
    response = qapi.request('/api/2.0/fo/knowledge_base/vuln', {'action': ...
    root = objectify.fromstring(response.encode('utf-8'))
```

This is my first real journey into Python 3, and strings etc.  If I'm to help in any PR's etc, I'd need time to grok this new (old!) world of 3.

Maybe @trolldbois can assist?

**Comment by stootles** [comment]
Looking at this myself. I have zero history and also just picking up python as my language to learn this year. So dont have the full story or background of the move to v3.x but thats what I am targetting.

I was getting (some) responses as byte strings that included the b'' markers, which was breaking lxml objectify fromstring() calls as it had a leading b' rather than starting with a <.

**Comment by stootles** [comment]
Playing with the encoding to make response a byte object broke some of the code when response is first assigned in the request method of connector.py

Changing the return line to read:
```
        return response.encode('ascii')
```
return a simple byte string that seemed to make the objectify fromstring() method work without needing to re-encode. However, this means the return is not a regular string.

I guess a choice needs to be make, should request return a string or a byte object?

:)

**Comment by trolldbois** [comment]
Just to be clear here, pull #42  is fixing the issue documented in this issue #40.
Specifically, the code previous was : return str(response.content), where response.content is a byte string, 
therefore str(bytesting) returns the string representation something like: "b\'<....>\'" , which is obviously not ok, because there is no standard way to go back to the original bytestring from there.

https://github.com/paragbaxi/qualysapi/issues/40#issuecomment-425693167 @lingfish comments is fixed in his next comment. Just encode the response.

https://github.com/paragbaxi/qualysapi/issues/40#issuecomment-426949713 by @lingfish is correct, 
I would advise users of lxml objectify to encode the unicode string response to get the bytestring that lxml wants. 
If you use xmltodict instead, it take unicode string instead of bytestring, so not need to encode the response.
Nothing need to change on top of #42.
Everything works.

**Comment by stootles** [comment]
The approach is great.

New to python and just trying to tie together some bits with QualysAPI. The reason lxml seemed relevant is that it is referenced in the examples heavily. There are a number of calls in qualys-example.py.

I'll update it and submit a PR
