### ISSUE TITLE
Connector broken?

### ISSUE THREAD

**Issue by pabb85** [paragbaxi/qualysapi#47]
Hi all,

It's been a while since I touched Qualys API but I'm getting back into it - back in the day I wrote my own connector in Perl but seeing this Python package exists seems great because it'll save a lot of time.

Despite this, it does not seem to work out of the box for me, i.e. the examples give the ltrim/int error, so there's something wrong with the parameters being passed in to the connector and also when I try to manually check connectivity, i.e. through the python console and doing a 'print a.request('about.php')' - I'm getting a 401 error as the connector tries to hit 'https://qualysapi.qualys.com/msp/about.php' ...

Has anybody tested/fixed the example files in a while?  Is there any guidance on changes that have happened which I need to beware of?

Thank you!
Paul

-

**Comment by paragbaxi** [comment]
@pabb85 uploaded new pip version. sorry about that. please try again.

**Comment by pabb85** [comment]
It does indeed work now - thank you kindly @paragbaxi  :)
