### ISSUE TITLE
Install and build fail with python2, pip install qualysapi only works with python3

### ISSUE THREAD

**Issue by 3133780X** [paragbaxi/qualysapi#55]
Running pip install qualysapi fails to locate any matching module. Running python3 -m pip install qualysapi finds the module and installs.

However, running the build command with python2 fails with error:
  File "setup.py", line 1
SyntaxError: encoding problem: future_fstrings

Running python3 setup.py build appears to work successfully; but running python3 setup.py install fails with this same error:
  File "setup.py", line 1
SyntaxError: encoding problem: future_fstring

**Comment by paragbaxi** [comment]
confirmed on py3.7
