### ISSUE TITLE
6.0.0 tag, but not pushed to Pypi?

### ISSUE THREAD

**Issue by lingfish** [paragbaxi/qualysapi#59]
Hi, as the subject says -- 6.0.0 seems to be git tagged, but in Pypi?

**Comment by lingfish** [comment]
Potentially related... you haven't bumped the version in:

https://github.com/paragbaxi/qualysapi/blob/6.0.0/qualysapi/version.py

:)

**Comment by paragbaxi** [comment]
pushed
