### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by CMeza99** [paragbaxi/qualysapi#74]
The `future_strings` is required to support f-strings in Python 3.5. Newer versions of Python support f-strings natively.

Python 3.5 is EOL Sept 13, 2020 (see https://devguide.python.org/#status-of-python-branches). If support is dropped a little early the code base and dependencies can be simplified.

The library has caused some confusion, see #73.

**Comment by paragbaxi** [comment]
sounds good. if anyone could produce PR i will merge
