### ISSUE TITLE
http_method not transmit after identification

### ISSUE THREAD

**Issue by batbast** [paragbaxi/qualysapi#88]
qualysapi code, maybe since 6.0 version, does not reuse the http_method identification between functions.
When I return http_method build into QDconnector.build_request function to calling functions, the correct http_method is used (POST by default, which is problematic with some API call).

3 lines to change:

`line 281: return url, data, headers, http_method`
`ligne 288: url, data, headers, http_method = self.build_request(api_call, data, api_version, http_method)`
`line 359: url, data, headers, http_method = self.build_request(api_call, data, api_version, http_method)`

Many thanks for your code.

**Comment by paragbaxi** [comment]
Happy to review a pull request.
