### ISSUE TITLE
connect() doesn't properly pull the correct API url

### ISSUE THREAD

**Issue by Macgyverops** [paragbaxi/qualysapi#95]
Recently had an issue transferring my script to another server.  Installed qualysapi (doesn't work for python2 but thats fine). But when attempting to do qualysapi.connect() it accepted my username and password but would not find the correct API base url.  (I am on qg3).  Not sure if this functionality was removed on Qualys' end as when I first used this a while back it worked just fine.

Adding the base url to the config file does the trick, but flat out won't work unless you put the correct url.  So effectively 

connect()
connect(username,password) 

Doesn't work.

**Comment by remidinishanth-ntnx** [comment]
I was also facing a similar issue, I've done the following

```python
qualysapi.connect(username='username', password='password', hostname='hostname')
a.auth = (username, password)
a.request('about.php')
```

And it worked
